/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BMICalculator;

import java.awt.print.PrinterException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paras
 */
public class BMICalculator extends javax.swing.JFrame {

    /**
     * Creates new form BMICalculator
     */
    public BMICalculator() {
        initComponents();
    }
    double weight, height, BMI;
    String op = null;//Sets all the buttons in the program to null

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jtxtweight = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jtxtheight = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jtxtbmi = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jtxtResults = new javax.swing.JTextField();
        jbtresults = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jtxtm = new javax.swing.JTextField();
        jtxtcm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtsummary = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("BMI CALCULATOR");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 940, 70));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setText("Enter your weight in Kilograms");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 390, 60));

        jtxtweight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtweightActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 160, 60));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField4.setText("Enter your height in meters");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 390, 60));

        jtxtheight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtheight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtheightActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 160, 60));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField6.setText("Your BMI is");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 390, 60));

        jtxtbmi.setEditable(false);
        jtxtbmi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtbmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtbmiActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtbmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 210, 60));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField8.setText("You are");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 390, 60));

        jtxtResults.setEditable(false);
        jtxtResults.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 210, 60));

        jbtresults.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtresults.setText("CALCULATE");
        jbtresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtresultsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtresults, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, 130));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("CM TO M Converter");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 140, 410, 60));

        jtxtm.setEditable(false);
        jtxtm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtmActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 210, 140, 60));

        jtxtcm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 140, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("m");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 220, 40, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("cm");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 40, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\paras\\Downloads\\icons8-convert-96.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 120, 110));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Your Personalized BMI Summary");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 430, 50));

        jtxtsummary.setEditable(false);
        jtxtsummary.setColumns(20);
        jtxtsummary.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtsummary.setLineWrap(true);
        jtxtsummary.setRows(5);
        jtxtsummary.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jtxtsummary);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, 780, 480));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\paras\\Downloads\\icons8-print-96.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 730, 120, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jtxtweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtweightActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jtxtheightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtheightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtheightActionPerformed

    private void jtxtbmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtbmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtbmiActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jtxtResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultsActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jbtresultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtresultsActionPerformed
        op = "Calculate";//Initializes the Calculate button
        double ans = 0;
        double rans = 0;
        weight = Double.parseDouble(jtxtweight.getText());//Gets and converts the weight string into a double
        height = Double.parseDouble(jtxtheight.getText());//Gets and converts the height string into a double
        
        if(op == "Calculate"){//Checks if the Calculate button in the program has been clicked. If it has been clicked the following command is executed
            ans = weight/(height*height);//Calculates the BMI of the user based on the information provided
            rans = Math.round(ans);//Rounds up the results
            jtxtbmi.setText(""+rans);//Displays the results in the text field.
            
            
        }
        if(rans<18.5){//Checks if the BMI result is less than 18.5
            jtxtResults.setText("Underweight");
            jtxtsummary.setText("If you're underweight, it's important to focus on nutrient-dense foods that can help you gain healthy weight. Here are some suggestions:\n" +
"\n" +
"Healthy Fats: Include sources of healthy fats in your diet such as avocados, nuts, seeds, and olive oil. These are calorie-dense and can help you increase your calorie intake.\n" +
"Protein-rich Foods: Protein is essential for building and repairing tissues. Include protein-rich foods like lean meats, poultry, fish, eggs, legumes, tofu, and dairy products in your meals.\n" +
"Complex Carbohydrates: Choose complex carbohydrates such as whole grains (brown rice, quinoa, whole wheat bread), oats, sweet potatoes, and fruits and vegetables. These provide energy and essential nutrients.\n" +
"Frequent Meals: Instead of three large meals, try to eat smaller, more frequent meals throughout the day. This can help increase your overall calorie intake.\n" +
"Nutrient-Dense Snacks: Snack on nutrient-dense foods like trail mix, Greek yogurt with fruit, cheese and whole-grain crackers, or nut butter with apple slices.\n" +
"Healthy Drinks: Avoid filling up on empty calories from sugary drinks. Instead, choose calorie-rich beverages like smoothies made with milk, protein powder, fruits, and nut butter.\n" +
"Strength Training: In addition to dietary changes, consider incorporating strength training exercises into your routine. Building muscle can help you gain weight in a healthy way.\n" +
"Consult a Dietitian: If you're struggling to gain weight, consider consulting a dietitian who can tailor a meal plan specifically to your needs and help you track your progress.\n" +
"Remember, it's essential to focus on gaining weight in a healthy way by consuming nutritious foods rather than relying on high-calorie, low-nutrient options.");
            
        }
        if(rans>18.5 && rans<24.9){//checks if the BMI result is between 18.5 and 24.9
            jtxtResults.setText("Normal");//If the BMI result is between 18.5 and 24.9. The jtxtResults field is set to Normal.
            jtxtsummary.setText("Your weight is normal. To ensure that you maintain a normal weight here are some tips and tricks:\n\n1.Balanced Diet: Focus on consuming a variety of nutrient-dense foods, including fruits, vegetables, whole grains, lean proteins, and healthy fats. Be mindful of the portion size and limit the intake of processed foods, sugary drinks, and high-calorie beverages.\n\n2.Regular Excersice: Incorporate regular physical activity into your routine. Aim for at least 150 minutes of moderate-intensity aerobic exercise or 75 minutes of vigorous-intensity aerobic exercise per week, along with muscle-strengthening activities on two or more days per week.\n\n3.Monitor Portions: Pay attention to portion sizes to prevent overeating. Use smaller plates and bowls, and be mindful of serving sizes when eating out.\n\n4.Stay Hydrated: Drink plenty of water throughout the day. Sometimes thirst can be mistaken for hunger, so staying hydrated can help prevent unnecessary snacking." );
        }
        if(rans>25 && rans<29.9){//checks if BMI is between 25 and 29.9
            jtxtResults.setText("Overweight");//If the BMI is between 25 and 29.9. The jtxtResults field is set to Overweight.
            jtxtsummary.setText("Losing weight in a healthy and sustainable way involves a combination of dietary changes, increased physical activity, and adopting healthier lifestyle habits. Here are some tips for losing weight if you are overweight:\n\n1. Set Realistic Goals: Set achievable and realistic weight loss goals. Aim for gradual weight loss of 1-2 pounds per week, which is considered safe and sustainable.\n\n2.Balanced Diet: Focus on eating a balanced diet that includes plenty of fruits, vegetables, whole grains, lean proteins, and healthy fats. Be mindful of portion sizes and avoid high-calorie, processed foods and sugary snacks.\n\n3.Calorie Deficit: To lose weight, you need to consume fewer calories than you burn. Calculate your daily calorie needs and create a calorie deficit by reducing your calorie intake and increasing your calorie expenditure through physical activity.\n\n4.Regular Exercise: Incorporate regular physical activity into your routine. Aim for at least 150 minutes of moderate-intensity aerobic exercise or 75 minutes of vigorous-intensity aerobic exercise per week, along with muscle-strengthening activities on two or more days per week.\n\n5.Cardiovascular Exercise: Include cardiovascular exercises such as walking, jogging, cycling, swimming, or aerobic classes to help burn calories and improve cardiovascular health.");
        }
        if(rans>=30){//checks if the BMI is greater than or equal to 30
            jtxtResults.setText("Obese");//If the BMI is greater than or equal to 30. The jtxtResults field is set to Obese.
            jtxtsummary.setText("If you are obese, it's important to take steps to improve your health and well-being. Here are some recommendations for managing obesity:\n\n1.Consult with a Healthcare Professional: Start by consulting with a healthcare professional, such as a doctor or a registered dietitian. They can assess your overall health, discuss your weight-related concerns, and provide personalized recommendations and support.\n\n2.Set Realistic Goals: Work with your healthcare provider to set realistic and achievable goals for weight loss and overall health improvement. Aim for gradual weight loss of 1-2 pounds per week, which is considered safe and sustainable.\n\n3.Healthy Eating: Focus on adopting a balanced and nutritious diet that includes plenty of fruits, vegetables, whole grains, lean proteins, and healthy fats. Limit the intake of processed foods, sugary snacks, and high-calorie beverages. Consider tracking your food intake and monitoring portion sizes to help manage calorie intake.\n\n4.Physical Activity: Incorporate regular physical activity into your routine. Aim for at least 150 minutes of moderate-intensity aerobic exercise or 75 minutes of vigorous-intensity aerobic exercise per week, along with muscle-strengthening activities on two or more days per week. Choose activities that you enjoy and can sustain in the long term.\n\n5.Behavioral Changes: Focus on making sustainable lifestyle changes, including mindful eating, stress management, and improving sleep habits. Identify triggers for unhealthy eating habits and develop strategies to overcome them. Consider seeking support from a counselor or behavioral therapist if needed.");
        }
        
    }//GEN-LAST:event_jbtresultsActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jtxtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        op = "convert";//Initializes convert to op
        double result = 0;
        double heightcm = Double.parseDouble(jtxtcm.getText());
        if(op =="convert"){//if the Convert button is clicked. The code in the if statement will be executed
            result = heightcm/100;//Divides the height in cm by 100 in order to obtain the height in meters and sets the value to result
            jtxtm.setText(""+result);//Displays the height in meters.
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try//The Print button
        {
            jtxtsummary.print();//prints the txtsummary text area.
        } catch (PrinterException ex) {
            Logger.getLogger(BMICalculator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMICalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMICalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMICalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMICalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMICalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton jbtresults;
    private javax.swing.JTextField jtxtResults;
    private javax.swing.JTextField jtxtbmi;
    private javax.swing.JTextField jtxtcm;
    private javax.swing.JTextField jtxtheight;
    private javax.swing.JTextField jtxtm;
    private javax.swing.JTextArea jtxtsummary;
    private javax.swing.JTextField jtxtweight;
    // End of variables declaration//GEN-END:variables
}
